//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="GPWS_CoreWebService")]
    public partial class User : object
    {
        
        private ServiceReference1.Assignment[] AssignmentsField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string LocationField;
        
        private bool LockedField;
        
        private string PasswordField;
        
        private string PhoneNumberField;
        
        private bool ResetPasswordField;
        
        private ulong SecurityMaskField;
        
        private string UserEmailField;
        
        private System.Guid UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Assignment[] Assignments
        {
            get
            {
                return this.AssignmentsField;
            }
            set
            {
                this.AssignmentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Locked
        {
            get
            {
                return this.LockedField;
            }
            set
            {
                this.LockedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ResetPassword
        {
            get
            {
                return this.ResetPasswordField;
            }
            set
            {
                this.ResetPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ulong SecurityMask
        {
            get
            {
                return this.SecurityMaskField;
            }
            set
            {
                this.SecurityMaskField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserEmail
        {
            get
            {
                return this.UserEmailField;
            }
            set
            {
                this.UserEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Assignment", Namespace="GPWS_CoreWebService")]
    public partial class Assignment : object
    {
        
        private string DataRootField;
        
        private long GroupIDField;
        
        private long IDField;
        
        private int InstanceIDField;
        
        private string InstanceNameField;
        
        private string NameField;
        
        private bool StatusField;
        
        private string TaskDescriptionField;
        
        private int TaskTypeField;
        
        private System.Guid UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataRoot
        {
            get
            {
                return this.DataRootField;
            }
            set
            {
                this.DataRootField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long GroupID
        {
            get
            {
                return this.GroupIDField;
            }
            set
            {
                this.GroupIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InstanceID
        {
            get
            {
                return this.InstanceIDField;
            }
            set
            {
                this.InstanceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstanceName
        {
            get
            {
                return this.InstanceNameField;
            }
            set
            {
                this.InstanceNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskDescription
        {
            get
            {
                return this.TaskDescriptionField;
            }
            set
            {
                this.TaskDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TaskType
        {
            get
            {
                return this.TaskTypeField;
            }
            set
            {
                this.TaskTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="GPWS_CoreWebService")]
    public partial class Transaction : object
    {
        
        private System.DateTime DateTimeField;
        
        private long IDField;
        
        private ServiceReference1.TollImage[] ImagesField;
        
        private int JurisdictionIDField;
        
        private string PlateField;
        
        private int ReviewCodeIDField;
        
        private long TaskIDField;
        
        private int TimeOfDayField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime
        {
            get
            {
                return this.DateTimeField;
            }
            set
            {
                this.DateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TollImage[] Images
        {
            get
            {
                return this.ImagesField;
            }
            set
            {
                this.ImagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JurisdictionID
        {
            get
            {
                return this.JurisdictionIDField;
            }
            set
            {
                this.JurisdictionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Plate
        {
            get
            {
                return this.PlateField;
            }
            set
            {
                this.PlateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReviewCodeID
        {
            get
            {
                return this.ReviewCodeIDField;
            }
            set
            {
                this.ReviewCodeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TaskID
        {
            get
            {
                return this.TaskIDField;
            }
            set
            {
                this.TaskIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeOfDay
        {
            get
            {
                return this.TimeOfDayField;
            }
            set
            {
                this.TimeOfDayField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TollImage", Namespace="GPWS_CoreWebService")]
    public partial class TollImage : object
    {
        
        private int CameraIDField;
        
        private long IDField;
        
        private string ImageNameField;
        
        private int JurisdictionField;
        
        private int JurisdictionScoreField;
        
        private string PathField;
        
        private short PerspectiveField;
        
        private string PlateField;
        
        private int PlateTypeField;
        
        private int ReviewCodeField;
        
        private int ScoreField;
        
        private int X1Field;
        
        private int X2Field;
        
        private int X3Field;
        
        private int X4Field;
        
        private int Y1Field;
        
        private int Y2Field;
        
        private int Y3Field;
        
        private int Y4Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CameraID
        {
            get
            {
                return this.CameraIDField;
            }
            set
            {
                this.CameraIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageName
        {
            get
            {
                return this.ImageNameField;
            }
            set
            {
                this.ImageNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Jurisdiction
        {
            get
            {
                return this.JurisdictionField;
            }
            set
            {
                this.JurisdictionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JurisdictionScore
        {
            get
            {
                return this.JurisdictionScoreField;
            }
            set
            {
                this.JurisdictionScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Perspective
        {
            get
            {
                return this.PerspectiveField;
            }
            set
            {
                this.PerspectiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Plate
        {
            get
            {
                return this.PlateField;
            }
            set
            {
                this.PlateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlateType
        {
            get
            {
                return this.PlateTypeField;
            }
            set
            {
                this.PlateTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReviewCode
        {
            get
            {
                return this.ReviewCodeField;
            }
            set
            {
                this.ReviewCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score
        {
            get
            {
                return this.ScoreField;
            }
            set
            {
                this.ScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int X1
        {
            get
            {
                return this.X1Field;
            }
            set
            {
                this.X1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int X2
        {
            get
            {
                return this.X2Field;
            }
            set
            {
                this.X2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int X3
        {
            get
            {
                return this.X3Field;
            }
            set
            {
                this.X3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int X4
        {
            get
            {
                return this.X4Field;
            }
            set
            {
                this.X4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Y1
        {
            get
            {
                return this.Y1Field;
            }
            set
            {
                this.Y1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Y2
        {
            get
            {
                return this.Y2Field;
            }
            set
            {
                this.Y2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Y3
        {
            get
            {
                return this.Y3Field;
            }
            set
            {
                this.Y3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Y4
        {
            get
            {
                return this.Y4Field;
            }
            set
            {
                this.Y4Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnResult", Namespace="GPWS_CoreWebService")]
    public partial class ReturnResult : object
    {
        
        private long IDField;
        
        private int JurisdictionIDField;
        
        private string PlateField;
        
        private int ReviewCodeIDField;
        
        private long TaskIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JurisdictionID
        {
            get
            {
                return this.JurisdictionIDField;
            }
            set
            {
                this.JurisdictionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Plate
        {
            get
            {
                return this.PlateField;
            }
            set
            {
                this.PlateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReviewCodeID
        {
            get
            {
                return this.ReviewCodeIDField;
            }
            set
            {
                this.ReviewCodeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TaskID
        {
            get
            {
                return this.TaskIDField;
            }
            set
            {
                this.TaskIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="GPWS_CoreWebService", ConfigurationName="ServiceReference1.IGPWS_CoreWebService")]
    public interface IGPWS_CoreWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="GPWS_CoreWebService/IGPWS_CoreWebService/Login", ReplyAction="GPWS_CoreWebService/IGPWS_CoreWebService/LoginResponse")]
        ServiceReference1.User Login(string strUserName, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="GPWS_CoreWebService/IGPWS_CoreWebService/Login", ReplyAction="GPWS_CoreWebService/IGPWS_CoreWebService/LoginResponse")]
        System.Threading.Tasks.Task<ServiceReference1.User> LoginAsync(string strUserName, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="GPWS_CoreWebService/IGPWS_CoreWebService/GetUserID", ReplyAction="GPWS_CoreWebService/IGPWS_CoreWebService/GetUserIDResponse")]
        System.Guid GetUserID();
        
        [System.ServiceModel.OperationContractAttribute(Action="GPWS_CoreWebService/IGPWS_CoreWebService/GetUserID", ReplyAction="GPWS_CoreWebService/IGPWS_CoreWebService/GetUserIDResponse")]
        System.Threading.Tasks.Task<System.Guid> GetUserIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="GPWS_CoreWebService/IGPWS_CoreWebService/StartAssignment", ReplyAction="GPWS_CoreWebService/IGPWS_CoreWebService/StartAssignmentResponse")]
        bool StartAssignment(long lngAssignmentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="GPWS_CoreWebService/IGPWS_CoreWebService/StartAssignment", ReplyAction="GPWS_CoreWebService/IGPWS_CoreWebService/StartAssignmentResponse")]
        System.Threading.Tasks.Task<bool> StartAssignmentAsync(long lngAssignmentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="GPWS_CoreWebService/IGPWS_CoreWebService/StopAssignment", ReplyAction="GPWS_CoreWebService/IGPWS_CoreWebService/StopAssignmentResponse")]
        bool StopAssignment();
        
        [System.ServiceModel.OperationContractAttribute(Action="GPWS_CoreWebService/IGPWS_CoreWebService/StopAssignment", ReplyAction="GPWS_CoreWebService/IGPWS_CoreWebService/StopAssignmentResponse")]
        System.Threading.Tasks.Task<bool> StopAssignmentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="GPWS_CoreWebService/IGPWS_CoreWebService/GetReview", ReplyAction="GPWS_CoreWebService/IGPWS_CoreWebService/GetReviewResponse")]
        ServiceReference1.Transaction GetReview();
        
        [System.ServiceModel.OperationContractAttribute(Action="GPWS_CoreWebService/IGPWS_CoreWebService/GetReview", ReplyAction="GPWS_CoreWebService/IGPWS_CoreWebService/GetReviewResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Transaction> GetReviewAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="GPWS_CoreWebService/IGPWS_CoreWebService/GetTransaction", ReplyAction="GPWS_CoreWebService/IGPWS_CoreWebService/GetTransactionResponse")]
        ServiceReference1.Transaction GetTransaction(long lngTransactionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="GPWS_CoreWebService/IGPWS_CoreWebService/GetTransaction", ReplyAction="GPWS_CoreWebService/IGPWS_CoreWebService/GetTransactionResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Transaction> GetTransactionAsync(long lngTransactionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="GPWS_CoreWebService/IGPWS_CoreWebService/SetResult", ReplyAction="GPWS_CoreWebService/IGPWS_CoreWebService/SetResultResponse")]
        bool SetResult(ServiceReference1.ReturnResult objReturnResult);
        
        [System.ServiceModel.OperationContractAttribute(Action="GPWS_CoreWebService/IGPWS_CoreWebService/SetResult", ReplyAction="GPWS_CoreWebService/IGPWS_CoreWebService/SetResultResponse")]
        System.Threading.Tasks.Task<bool> SetResultAsync(ServiceReference1.ReturnResult objReturnResult);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IGPWS_CoreWebServiceChannel : ServiceReference1.IGPWS_CoreWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class GPWS_CoreWebServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IGPWS_CoreWebService>, ServiceReference1.IGPWS_CoreWebService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GPWS_CoreWebServiceClient() : 
                base(GPWS_CoreWebServiceClient.GetDefaultBinding(), GPWS_CoreWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_IGPWS_CoreWebService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GPWS_CoreWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(GPWS_CoreWebServiceClient.GetBindingForEndpoint(endpointConfiguration), GPWS_CoreWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GPWS_CoreWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GPWS_CoreWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GPWS_CoreWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GPWS_CoreWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GPWS_CoreWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference1.User Login(string strUserName, string strPassword)
        {
            return base.Channel.Login(strUserName, strPassword);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.User> LoginAsync(string strUserName, string strPassword)
        {
            return base.Channel.LoginAsync(strUserName, strPassword);
        }
        
        public System.Guid GetUserID()
        {
            return base.Channel.GetUserID();
        }
        
        public System.Threading.Tasks.Task<System.Guid> GetUserIDAsync()
        {
            return base.Channel.GetUserIDAsync();
        }
        
        public bool StartAssignment(long lngAssignmentID)
        {
            return base.Channel.StartAssignment(lngAssignmentID);
        }
        
        public System.Threading.Tasks.Task<bool> StartAssignmentAsync(long lngAssignmentID)
        {
            return base.Channel.StartAssignmentAsync(lngAssignmentID);
        }
        
        public bool StopAssignment()
        {
            return base.Channel.StopAssignment();
        }
        
        public System.Threading.Tasks.Task<bool> StopAssignmentAsync()
        {
            return base.Channel.StopAssignmentAsync();
        }
        
        public ServiceReference1.Transaction GetReview()
        {
            return base.Channel.GetReview();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Transaction> GetReviewAsync()
        {
            return base.Channel.GetReviewAsync();
        }
        
        public ServiceReference1.Transaction GetTransaction(long lngTransactionID)
        {
            return base.Channel.GetTransaction(lngTransactionID);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Transaction> GetTransactionAsync(long lngTransactionID)
        {
            return base.Channel.GetTransactionAsync(lngTransactionID);
        }
        
        public bool SetResult(ServiceReference1.ReturnResult objReturnResult)
        {
            return base.Channel.SetResult(objReturnResult);
        }
        
        public System.Threading.Tasks.Task<bool> SetResultAsync(ServiceReference1.ReturnResult objReturnResult)
        {
            return base.Channel.SetResultAsync(objReturnResult);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IGPWS_CoreWebService))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_IGPWS_CoreWebService))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://gas-iis003.globalagility.solutions/GPWS_CoreWebService/GPWS_CoreWebServ" +
                        "ice.svc/GPWS_CoreWebService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GPWS_CoreWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_IGPWS_CoreWebService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GPWS_CoreWebServiceClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_IGPWS_CoreWebService);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_IGPWS_CoreWebService,
        }
    }
}
